### ISSUE TITLE
Failed to activate the sort-lines package

### ISSUE THREAD

**Issue by FRKodes** [atom/sort-lines#38] opened 2015-10-06 15:05 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [sort-lines](https://github.com/atom/sort-lines) package, v0.11.0

### Stack Trace

Failed to activate the sort-lines package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (/Users/antoniocalderonjeronimo/.atom/packages/sort-lines/lib/sort-lines.coffee:5:10)
  at Package.module.exports.Package.activateNow (/Users/antoniocalderonjeronimo/Documents/Software/Atom.app/Contents/Resources/app.asar/src/package.js:245:19)
  at /Users/antoniocalderonjeronimo/Documents/Software/Atom.app/Contents/Resources/app.asar/src/package.js:838:25
  at Emitter.module.exports.Emitter.emit (/Users/antoniocalderonjeronimo/Documents/Software/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/antoniocalderonjeronimo/Documents/Software/Atom.app/Contents/Resources/app.asar/src/command-registry.js:226:20)
  at /Users/antoniocalderonjeronimo/Documents/Software/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/antoniocalderonjeronimo/Documents/Software/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/antoniocalderonjeronimo/Documents/Software/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Users/antoniocalderonjeronimo/Documents/Software/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -4:17.6.0 window:reset-font-size (atom-text-editor.editor.is-focused)
     -4:13.9.0 settings-view:open (atom-text-editor.editor.is-focused)
     -2:38.6.0 core:backspace (atom-text-editor#editor.fontSize.editor.mini.is-focused)
     -1:05.6.0 pane:split-left (atom-text-editor.editor.is-focused)
     -0:10.2.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  3x -0:09.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:08.6.0 core:move-to-bottom (atom-text-editor.editor.is-focused)
     -0:07.8.0 core:move-to-top (atom-text-editor.editor.is-focused)
     -0:07.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:06.9.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:06.4.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
 13x -0:06.0 core:move-down (atom-text-editor.editor.is-focused)
  7x -0:04.4.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:03.2.0 core:move-right (atom-text-editor.editor.is-focused)
  5x -0:02.9.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:00.8.0 sort-lines:sort (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "themes": [
      "one-dark-ui",
      "hydra-syntax-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
editor-stats, v0.17.0
emmet, v2.3.13
hydra-syntax-theme, v0.2.4
minimap, v4.13.4
sort-lines, v0.11.0

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-10-12 15:04
@FRKodes Can you reliably reproduce this problem? And can you share the contents of this file:

```
/Users/antoniocalderonjeronimo/.atom/packages/sort-lines/lib/sort-lines.coffee
```

**Comment by FRKodes** [comment] 2015-10-13 14:42
Hi @izuzak thanks for your time, well, when I have some text selected and try to sort it with F5, Atom gets me a message that says something like "unknown problem" or so.

The content of the sort-lines.cofee file is:

RangeFinder = require './range-finder'

module.exports =
  activate: ->
    atom.commands.add 'atom-text-editor',
      'sort-lines:sort': ->
        editor = atom.workspace.getActiveTextEditor()
        sortLines(editor)
      'sort-lines:reverse-sort': ->
        editor = atom.workspace.getActiveTextEditor()
        sortLinesReversed(editor)
      'sort-lines:unique': ->
        editor = atom.workspace.getActiveTextEditor()
        uniqueLines(editor)
      'sort-lines:case-insensitive-sort': ->
        editor = atom.workspace.getActiveTextEditor()
        sortLinesInsensitive(editor)

sortTextLines = (editor, sorter) ->
  sortableRanges = RangeFinder.rangesFor(editor)
  sortableRanges.forEach (range) ->
    textLines = editor.getTextInBufferRange(range).split("\n")
    textLines = sorter(textLines)
    editor.setTextInBufferRange(range, textLines.join("\n"))

sortLines = (editor) ->
   sortTextLines editor, (textLines) ->
    textLines.sort (a, b) -> a.localeCompare(b)

sortLinesReversed = (editor) ->
   sortTextLines editor, (textLines) ->
    textLines.sort (a, b) -> b.localeCompare(a)

uniqueLines = (editor) ->
   sortTextLines editor, (textLines) ->
    textLines.filter (value, index, self) -> self.indexOf(value) == index

sortLinesInsensitive = (editor) ->
   sortTextLines editor, (textLines) ->
    textLines.sort (a, b) -> a.toLowerCase().localeCompare(b.toLowerCase())


Once again, thanks for your time man.

Greetings from Guadalajara México.

**Comment by izuzak** [comment] 2015-10-20 07:53
Thanks for that information, @FRKodes -- I have to admit that I don't have an idea why that might be happening, so I'm going to ping @nathansobo for more :eyes:.

Also, @FRKodes can you try reproducing the problem with all other packages you have installed disabled? So, go to Atom's settings, disable these 4 packages you installed, and then restart Atom and see if you can still reproduce the problem:

```
editor-stats, v0.17.0
emmet, v2.3.13
hydra-syntax-theme, v0.2.4
minimap, v4.13.4
```

Thanks!

**Comment by FRKodes** [comment] 2015-10-20 15:13
Hi @izuzak , there is no problem dude, by the way I don't know what happened, i just woke up today and it's working.

Sorry for the drawback, thanks for your time.

**Comment by nathansobo** [comment] 2015-10-20 15:21
Since it's working I'll close this out. Please reopen if the problem happens again.

**Closed by nathansobo** 2015-10-20 15:21 UTC
Labels: bug, needs-reproduction, uncaught-exception
