### ISSUE TITLE
JSON keys are sorted in wrong order

### ISSUE THREAD

**Issue by danieltian** [atom/sort-lines#25] opened 2015-04-22 18:06 UTC
The following JSON:

    {
        "abc": "123",
        "abc_def": "123",
        "abc_def_ghi": "123"
    }

is sorted to:

    {
        "abc_def_ghi": "123"
        "abc_def": "123",
        "abc": "123"
    }

It should be sorted to the first version.

**Comment by danieltian** [comment] 2015-04-22 20:18
I investigated this a little, it seems like there's an issue with the double quote and `localeCompare`. This sorts properly:

    a
    a_b
    a_b_c

So does this:

    "a
    "a_b
    "a_b_c

But once you enclose it in quotes, it sorts wrong:

    "a"
    "a_b"
    "a_b_c"

It seems like it's related to locale. If you use:

    a.localeCompare(b, { ignorePunctuation: true })

it still sorts incorrectly, but once you add in a locale:

    a.localeCompare(b, 'en-US', { ignorePunctuation: true })

then it sorts properly.

**Comment by viveleroi** [comment] 2015-08-18 17:23
I'm seeing something similar in CSS/SCSS files. Any hyphenated keys are sorted before the original, so "border-radius" is placed before "border".

Reproduced by entering the following (in any order) in a css file and sorting via F5:

    border-radius: 5px;
    border-width: 2px;
    border: 1px;

They're sorted into the above order, which isn't incorrect.

**Comment by 50Wliu** [comment] 2016-01-14 02:31
This looks like it'll be fixed by #36.

**Comment by abdonrd** [comment] 2016-02-15 20:55
+1

**Comment by lee-dohm** [comment] 2016-02-15 22:24
This was fixed with the addition of [natural sort](https://github.com/atom/sort-lines/pull/50).

**Closed by lee-dohm** 2016-02-15 22:24 UTC
Labels: bug
