### ISSUE TITLE
Sort ignores the selection.

### ISSUE THREAD

**Issue by tregusti** [atom/sort-lines#45] opened 2015-11-04 11:58 UTC
I just updated the plugin to 0.12.0. And sorting with a selection always sorts the whole file now, not only the selected lines.

**Comment by harshpatel19** [comment] 2015-11-05 11:14
I have the same issue.

**Comment by olivertappin** [comment] 2015-11-05 14:12
I'm also having this issue however, when you select the lines you want to sort and use the keyboard shortcut to sort them it sorts the whole file but if you `cmd-z` it will have sorted your selected lines. A quick work around for now. Seems like it's running the command for the selection and then the whole file within the same action.

**Comment by tregusti** [comment] 2015-11-05 14:13
Thank you @olivertappin for the info!

**Comment by lczech** [comment] 2016-01-14 23:53
Same with version 0.13.0

**Comment by lee-dohm** [comment] 2016-01-15 00:46
I just tried this with v0.13.0 on Atom v1.5.0-dev-c34ef24 on Mac OS X 10.11.2 and I can't reproduce the issue. Here's what I did:

1. Opened a file and found two lines that are misordered
1. Selected from partway through the first to partway through the second
1. Triggered sort-lines using <kbd>F5</kbd>

**Expected and Actual:** The two lines swapped places

Then I used <kbd>Cmd+Z</kbd> to reset the file back to the beginning stated and did:

1. Selected from partway through the  first line to several characters before the end of the same line
1. Triggered sort-lines using <kbd>F5</kbd>

**Expected and Actual:** Nothing changed

And finally, just to make sure that the entire file sorting wasn't broken, I deselected everything and pressed <kbd>F5</kbd> and the whole file sorted.

If someone has repro steps that I haven't already tried, let us know!

**Comment by ernestoalejo** [comment] 2016-01-15 00:48
When I press F9 (`'f9': 'sort-lines:sort'` in keybindings) the full file gets sorted. v0.13.0 on Linux.

**Comment by ernestoalejo** [comment] 2016-01-15 00:49
Well in fact, as @olivertappin said, it first orders the selected lines and then goes to order the whole file.

**Comment by lee-dohm** [comment] 2016-01-15 00:50
@ernestoalejo I can't reproduce that behavior.

**Comment by ernestoalejo** [comment] 2016-01-15 00:51
Maybe it's Atom version? I have 1.3.3 (the one in the homepage)

**Comment by lee-dohm** [comment] 2016-01-15 00:53
You may want to update to the latest version, v1.4.0 is the version on the homepage now.

**Comment by lczech** [comment] 2016-01-15 00:53
I can reproduce, with the exact steps @lee-dohm described.
@ernestoalejo uses Linux, so do I. Maybe that's the reason?

atom 1.4.0
sort 0.13.0
ubuntu 14.4

**Comment by ernestoalejo** [comment] 2016-01-15 01:06
oh, I can't reproduce the bug anymore after the update. I'm using Fedora, `atom-1.4.0-0.1.fc21.x86_64` if it helps somebody.

**Comment by dbslone** [comment] 2016-01-18 08:11
I just upgraded to sort 0.13.0 and now the entire file is sorted instead of the highlighted section. I'm using atom 1.4.0 on OS X 10.11.2.

**Comment by lee-dohm** [comment] 2016-01-18 08:15
@dbslone I can't reproduce the issue you're describing on Atom v1.4.0 on Mac OS X 10.11.2. Can you give more specific repro steps? Here's what I did:

1. Launch Atom
1. Select a few lines of my `config.cson`
1. Press <kbd>Shift+Cmd+P</kbd> to open the Command Palette
1. Type `sort` to bring "Sort Lines: Sort" to the top
1. Press <kbd>Enter</kbd>

**Expected and Actual:** Just the selected lines were sorted

**Comment by dbslone** [comment] 2016-01-18 08:27
@lee-dohm In hopes to give an accurate step by step on how to reproduce the error I closed my currently running instance of atom and when I reopened it sort was only sorting the selected lines. I feel like the boy who cried wolf right now.

I was working on a jsx file for a React component and I highlighted my 5 props for the component and pressed `F5` instead of seeing the 5 lines of code I selected being sorted the actual result was the entire document was sorted line by line with blank lines at the top of the file.

**Comment by lee-dohm** [comment] 2016-01-18 08:34
@dbslone Had you updated the sort-lines package in the Settings View **without** restarting Atom just before you experienced this problem? I have a theory on what might have happened, but it is really late here and I have to get some sleep. Let me know and I'll take a look at it when I can tomorrow.

Thanks!

**Comment by dbslone** [comment] 2016-01-18 08:36
@lee-dohm Yeah I just updated the sort-lines package in the Settings View without restarting when I started experiencing the problem. And after a restart of Atom that seemed to resolve the issue.

**Comment by lczech** [comment] 2016-01-18 12:34
Same here. Restarting atom now solved the issue.

As this seems to be fixed in the current version, and assuming that most users restart atom eventually, this issue can probably be closed ;-)

**Comment by lee-dohm** [comment] 2016-01-18 17:51
Since the underlying issue is fixed I'm going to close this. Thanks everyone for your help! :grinning:

**Closed by lee-dohm** 2016-01-18 17:51 UTC
Labels: bug, needs-reproduction
