### ISSUE TITLE
Default keybinding for F5 is very bad.

### ISSUE THREAD

**Issue by ericnewton76** [atom/sort-lines#71] opened 2017-04-19 21:34 UTC
F5 is usually "refresh" or "reload"

Please take this out of your default keybinding.

Allows users to decide that F5 is great for sorting instead of normal convention of refreshing/reloading

**Comment by rsese** [comment] 2017-04-24 08:14
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/sort-lines/issues/31 and it looks like you found the PR where it was proposed to remove this keybinding and commented there. Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-04-24 08:14 UTC
