### ISSUE TITLE
Bug: F5 sorts entire file, not selection

### ISSUE THREAD

**Issue by spanktar** [atom/sort-lines#74] opened 2017-05-09 17:18 UTC
Atom: 1.16.0 OSX
sort-lines: 0.14.0

When I make a selection then use F5, the entire file gets sorted, not just the selection.  Oddly, when I Undo, the selection is then sorted.  Very strange.

**Comment by rsese** [comment] 2017-05-09 21:26
Hmmm, I'm unable to reproduce - can you reproduce in safe mode (`atom --safe`)?

**Comment by lee-dohm** [comment] 2017-10-30 20:06
Thanks for reaching out!

We haven't gotten a response to our questions in our comment https://github.com/atom/sort-lines/issues/74#issuecomment-300306436. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by lee-dohm** 2017-10-30 20:06 UTC
Labels: more-information-needed
